In [ ]:
import pandas as pd
import numpy as np
from functools import reduce
df =pd.read_csv('/content/datasets/BL-Flickr-Images-Book.csv')
df.tail()
df.info()
to_drop=['Edition Statement','Corporate Author','Corporate Contributors','Former owner','Engraver','Contributors','Issuance type','Shelfmarks']
df.drop(to_drop,inplace=True,axis=1)
df.head()
df.info()
df.set_index('Identifier',inplace=True)
df.head()
df['Date of Publication'].head(25)
unwanted_characters=['[',',','-']
def clean_dates(item):
  dop=str(item.loc['Date of Publication'])
  if dop=='nan' or dop[0]=='[':
    return np.NAN
  for character in unwanted_characters:
    if character in dop:
      character_index=dop.find(character)
      dop=dop[:character_index]
  return dop
df['Date of Publication']=df.apply(clean_dates,axis=1)
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8287 entries, 0 to 8286
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Identifier              8287 non-null   int64
 1   Edition Statement       773 non-null    object
 2   Place of Publication    8287 non-null   object
 3   Date of Publication     8106 non-null   object
 4   Publisher               4092 non-null   object
 5   Title                   8287 non-null   object
 6   Author                  6509 non-null   object
 7   Contributors            8287 non-null   object
 8   Corporate Author        0 non-null      float64
 9   Corporate Contributors  0 non-null      float64
 10  Former owner            1 non-null      object
 11  Engraver                0 non-null      float64
 12  Issuance type           8287 non-null   object
 13  Flickr URL              8287 non-null   object
 14  Shelfmarks              8287 non-null   object
dtypes: float64(3), int64(1), object(11)
memory usage: 971.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8287 entries, 0 to 8286
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Identifier            8287 non-null   int64
 1   Place of Publication  8287 non-null   object
 2   Date of Publication   8106 non-null   object
 3   Publisher             4092 non-null   object
 4   Title                 8287 non-null   object
 5   Author                6509 non-null   object
 6   Flickr URL            8287 non-null   object
dtypes: int64(1), object(6)
memory usage: 453.3+ KB

,Place of Publication,Date of Publication,Publisher,Title,Author,Flickr URL
Identifier,,,,,,
206,London,1879,S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,http://www.flickr.com/photos/britishlibrary/ta...
216,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
218,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
472,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
480,London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...

In [ ]:
import pandas as pd
import numpy as np
from functools import reduce
df=pd.read_csv('/content/datasets/BL-Flickr-Images-Book.csv')
df.head()
df.info()
to_drop=['Edition Statement','Shelfmarks']
df.drop(to_drop,inplace=True,axis=1)
df.head()
df.info()
df.set_index('Identifier',inplace=True)
df.head()
df['Date of Publication'].head(25)
unwanted_character=['[',',','_']
def clean_dates(item):
  dop=str(item.loc['Date of Publication'])
  if dop=='nan'or dop[0]=='[':
    return np.NAN
  for character in unwanted_character:
    if character in dop:
      character_index=dop.find(character)
      dop=dop[:character_index]
  return dop
df['Date of Publication']=df.apply(clean_dates,axis=1)
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8287 entries, 0 to 8286
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Identifier              8287 non-null   int64
 1   Edition Statement       773 non-null    object
 2   Place of Publication    8287 non-null   object
 3   Date of Publication     8106 non-null   object
 4   Publisher               4092 non-null   object
 5   Title                   8287 non-null   object
 6   Author                  6509 non-null   object
 7   Contributors            8287 non-null   object
 8   Corporate Author        0 non-null      float64
 9   Corporate Contributors  0 non-null      float64
 10  Former owner            1 non-null      object
 11  Engraver                0 non-null      float64
 12  Issuance type           8287 non-null   object
 13  Flickr URL              8287 non-null   object
 14  Shelfmarks              8287 non-null   object
dtypes: float64(3), int64(1), object(11)
memory usage: 971.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8287 entries, 0 to 8286
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Identifier              8287 non-null   int64
 1   Place of Publication    8287 non-null   object
 2   Date of Publication     8106 non-null   object
 3   Publisher               4092 non-null   object
 4   Title                   8287 non-null   object
 5   Author                  6509 non-null   object
 6   Contributors            8287 non-null   object
 7   Corporate Author        0 non-null      float64
 8   Corporate Contributors  0 non-null      float64
 9   Former owner            1 non-null      object
 10  Engraver                0 non-null      float64
 11  Issuance type           8287 non-null   object
 12  Flickr URL              8287 non-null   object
dtypes: float64(3), int64(1), object(9)
memory usage: 841.8+ KB

,Place of Publication,Date of Publication,Publisher,Title,Author,Contributors,Corporate Author,Corporate Contributors,Former owner,Engraver,Issuance type,Flickr URL
Identifier,,,,,,,,,,,,
206,London,1879,S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,"FORBES, Walter.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...
216,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...
218,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...
472,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.","Appleyard, Ernest Silvanus.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...
480,London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.","BROOME, John Henry.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...